{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "saturn-monitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "saturn-monitor.labels" . | nindent 4 }}
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "saturn-monitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "saturn-monitor.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "saturn-monitor.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "saturn-monitor.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
