apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-job
  namespace: default
spec:
  schedule: "0 3 * * *"  # Every day at 3 AM
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: Saturn-monitor
          restartPolicy: OnFailure
          
          containers:
          # Your main job container
          - name: backup
            image: your-backup-image:latest
            command: ["/bin/sh"]
            args: ["-c", "/scripts/backup.sh"]
            resources:
              limits:
                cpu: "1"
                memory: 1Gi
              requests:
                cpu: 250m
                memory: 256Mi
          
          # Saturn sidecar
          - name: Saturn-sidecar
            image: Saturn/k8s-sidecar:1.0.0
            env:
            - name: PULSEGUARD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: Saturn-token
                  key: token
            - name: PULSEGUARD_API
              value: "https://api.Saturn.com"
            - name: CRONJOB_NAME
              value: "backup-job"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MAIN_CONTAINER_NAME
              value: "backup"
            - name: CAPTURE_OUTPUT
              value: "true"
            - name: MAX_OUTPUT_BYTES
              value: "10240"
            resources:
              limits:
                cpu: 100m
                memory: 128Mi
              requests:
                cpu: 50m
                memory: 64Mi

---
apiVersion: v1
kind: Secret
metadata:
  name: Saturn-token
  namespace: default
type: Opaque
stringData:
  # Get this token from Saturn dashboard
  token: "pg_your_token_here"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: Saturn-monitor
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: Saturn-monitor
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: Saturn-monitor
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: Saturn-monitor
subjects:
- kind: ServiceAccount
  name: Saturn-monitor
  namespace: default






