/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Saturn",
  "tagline": "Stop guessing. Start knowing.",
  "favicon": "img/favicon.ico",
  "url": "https://docs.saturn.example.com",
  "baseUrl": "/",
  "organizationName": "saturn",
  "projectName": "saturn-docs",
  "onBrokenLinks": "throw",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "markdown": {
    "mermaid": true,
    "format": "mdx",
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  },
  "themes": [
    "@docusaurus/theme-mermaid"
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "routeBasePath": "/",
          "sidebarPath": "./sidebars.ts",
          "editUrl": "https://github.com/saturn/saturn/tree/main/website/"
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        },
        "sitemap": {
          "changefreq": "weekly",
          "priority": 0.5,
          "ignorePatterns": [
            "/tags/**"
          ],
          "filename": "sitemap.xml"
        }
      }
    ],
    [
      "redocusaurus",
      {
        "specs": [
          {
            "spec": "static/openapi.yaml",
            "route": "/api/reference"
          }
        ],
        "theme": {
          "primaryColor": "#1890ff"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/saturn-og.png",
    "navbar": {
      "title": "Saturn",
      "logo": {
        "alt": "Saturn Logo",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "docsSidebar",
          "position": "left",
          "label": "Docs"
        },
        {
          "to": "/api/reference",
          "position": "left",
          "label": "API"
        },
        {
          "href": "https://status.saturn.example.com",
          "label": "Status",
          "position": "right"
        },
        {
          "href": "https://github.com/saturn",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Get Started",
              "to": "/get-started/overview"
            },
            {
              "label": "Kubernetes",
              "to": "/kubernetes/sidecar"
            },
            {
              "label": "WordPress",
              "to": "/wordpress/install"
            },
            {
              "label": "API Reference",
              "to": "/api/reference"
            }
          ]
        },
        {
          "title": "Product",
          "items": [
            {
              "label": "Pricing",
              "href": "https://saturn.example.com/pricing"
            },
            {
              "label": "Status",
              "href": "https://status.saturn.example.com"
            },
            {
              "label": "Changelog",
              "to": "/changelog"
            },
            {
              "label": "Roadmap",
              "to": "/roadmap"
            }
          ]
        },
        {
          "title": "Legal",
          "items": [
            {
              "label": "Privacy Policy",
              "to": "/legal/privacy"
            },
            {
              "label": "Terms of Service",
              "to": "/legal/terms"
            },
            {
              "label": "DPA",
              "to": "/legal/dpa"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/saturn"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/saturn"
            },
            {
              "label": "Contact",
              "to": "/contact"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 Saturn. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash",
        "json",
        "yaml",
        "typescript",
        "javascript",
        "go",
        "php"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "metadata": [
      {
        "name": "keywords",
        "content": "cron monitoring, kubernetes cronjob, wp-cron, anomaly detection, job monitoring, MTTR, MTBF"
      },
      {
        "name": "description",
        "content": "Anomaly-aware monitoring for cron, Kubernetes CronJobs, and wp-cron — with health scores, MTTR/MTBF, and multi-channel alerts."
      },
      {
        "property": "og:type",
        "content": "website"
      },
      {
        "property": "og:description",
        "content": "Anomaly-aware monitoring for cron, Kubernetes CronJobs, and wp-cron — with health scores, MTTR/MTBF, and multi-channel alerts."
      },
      {
        "name": "twitter:card",
        "content": "summary_large_image"
      },
      {
        "name": "twitter:description",
        "content": "Anomaly-aware monitoring for cron, Kubernetes CronJobs, and wp-cron — with health scores, MTTR/MTBF, and multi-channel alerts."
      }
    ],
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "mermaid": {
      "theme": {
        "dark": "dark",
        "light": "default"
      },
      "options": {}
    }
  },
  "plugins": [
    [
      "/home/roshan/development/personal/pulse-guard/website/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/index.js",
      {
        "hashed": true,
        "language": [
          "en"
        ],
        "highlightSearchTermsOnTargetPage": true,
        "explicitSearchResultPath": true
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
