apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cronjob.name }}-tokiflow
  labels:
    app: {{ .Values.cronjob.name }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  token: {{ .Values.tokiflow.token | quote }}





