apiVersion: v2
name: Saturn-monitor
description: Zero-code monitoring for Kubernetes CronJobs with Saturn
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - monitoring
  - cronjob
  - alerting
  - observability
home: https://Saturn.co
sources:
  - https://github.com/Saturn/Saturn
maintainers:
  - name: Saturn Team
    email: support@Saturn.co
icon: https://Saturn.co/icon.png




